/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Marco Antonio
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        dspEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        itemHistorial = new javax.swing.JMenu();
        itemClientes = new javax.swing.JMenuItem();
        itemMascotas = new javax.swing.JMenuItem();
        itemTipos = new javax.swing.JMenuItem();
        itemCitas = new javax.swing.JMenuItem();
        itemServicios = new javax.swing.JMenuItem();
        itemEmpleados = new javax.swing.JMenuItem();
        ItemHistorial = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemProcesos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemCuenta = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        itemReporte = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        itemGuia = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        itemCreadores = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dspEscritorio.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout dspEscritorioLayout = new javax.swing.GroupLayout(dspEscritorio);
        dspEscritorio.setLayout(dspEscritorioLayout);
        dspEscritorioLayout.setHorizontalGroup(
            dspEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        dspEscritorioLayout.setVerticalGroup(
            dspEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(135, 204, 204));

        itemHistorial.setBackground(new java.awt.Color(135, 204, 204));
        itemHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mantenimiento (2).png"))); // NOI18N
        itemHistorial.setText("Mantenimiento");

        itemClientes.setText("Clientes");
        itemHistorial.add(itemClientes);

        itemMascotas.setText("Mascotas");
        itemHistorial.add(itemMascotas);

        itemTipos.setText("Tipo de Mascota");
        itemHistorial.add(itemTipos);

        itemCitas.setText("Citas");
        itemCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCitasActionPerformed(evt);
            }
        });
        itemHistorial.add(itemCitas);

        itemServicios.setText("Servicios");
        itemHistorial.add(itemServicios);

        itemEmpleados.setText("Empleados");
        itemHistorial.add(itemEmpleados);

        ItemHistorial.setText("Historial Clinico");
        ItemHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemHistorialActionPerformed(evt);
            }
        });
        itemHistorial.add(ItemHistorial);

        jMenuBar1.add(itemHistorial);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flujo-de-trabajo (2).png"))); // NOI18N
        jMenu2.setText("Procesos");

        itemProcesos.setText("Procesos del Citas");
        jMenu2.add(itemProcesos);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/negocio (2).png"))); // NOI18N
        jMenu5.setText("Cuenta de Resultados");

        itemCuenta.setText("Cuenta de Servicios");
        jMenu5.add(itemCuenta);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte (1).png"))); // NOI18N
        jMenu6.setText("Reportes");

        itemReporte.setText("Reporte de Procesos Servicios");
        jMenu6.add(itemReporte);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayudar.png"))); // NOI18N
        jMenu7.setText("Ayuda");

        itemGuia.setText("Guia de usuario");
        jMenu7.add(itemGuia);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/anonimo.png"))); // NOI18N
        jMenu8.setText("Autores");

        itemCreadores.setText("Creadores del programa");
        jMenu8.add(itemCreadores);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dspEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dspEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCitasActionPerformed

    private void ItemHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem ItemHistorial;
    public javax.swing.JDesktopPane dspEscritorio;
    public javax.swing.JMenuItem itemCitas;
    public javax.swing.JMenuItem itemClientes;
    public javax.swing.JMenuItem itemCreadores;
    public javax.swing.JMenuItem itemCuenta;
    public javax.swing.JMenuItem itemEmpleados;
    public javax.swing.JMenuItem itemGuia;
    private javax.swing.JMenu itemHistorial;
    public javax.swing.JMenuItem itemMascotas;
    public javax.swing.JMenuItem itemProcesos;
    public javax.swing.JMenuItem itemReporte;
    public javax.swing.JMenuItem itemServicios;
    public javax.swing.JMenuItem itemTipos;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
